name: 私服投稿
description: 向我们投稿私服文件，以便在未来可使用安装器直接安装该私服。
title: "[ServerAdd]: "
labels: ["HopeServer"]
assignees:
  - QingFeng-awa
type: Feature
projects: ["QingFengTechnology/2"]
body:
  - type: input
    attributes:
      label: 该私服的简称是什么?
    validations:
      required: true
  - type: input
    attributes:
      label: 该私服所有者的中国社交媒体账号链接为?
      description: 此处只接受 bilibili(填写主页链接) / 中国版抖音(填写抖音号) / QQ(填写 QQ 号)。<br>第三方投稿的私服所有者必须拥有中国社交媒体账号。
    validations:
      required: true
  - type: dropdown
    attributes:
      label: 该私服成立时间已有多久?
      options:
        - 7 天内
        - 7 天 - 60 天
        - 60 天 - 180 天
        - 180 天 - 1 年
        - 1 年以上
    validations:
      required: true
  - type: dropdown
    attributes:
      label: 该私服拥有多少个服务器?
      description: 一个服务器的不同版本服务端也算，请以`regionInfo.json`内的数量为准。
      options:
        - 1 个
        - 2 - 3 个
        - 4 个及以上
    validations:
      required: true
  - type: input
    attributes: 
      label: 该私服的`regionInfo.json`是否拥有可长期稳定使用的在线更新链接?如果有，请提供。
  - type: textarea
    attributes:
      label: 请提供该私服的`regionInfo.json`。
      description: 将`regionInfo.json`的内容粘贴到此处即可，此处不需要 Markdown 的格式化反引号。
      render: json
    validations:
      required: true
  - type: input
    attributes:
      label: 该私服是否有官方 QQ 群?如果有，请提供。
      description: 尽量填写群号，但也可填写分享链接(风险自负)。<br>请确保该群聊允许被公开传播。
  - type: input
    attributes:
      label: 该私服是否有官方网站?如果有，请提供。
      description: 请确保该网站允许被公开传播。